### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by Dominicthecodingenuis** [snipergaming888/BTD6-MM---INSTA-Farm#1]
umm hi I just need to know so my friend from school said that this is is his account  and he said he got hacked but i think he is lying so are you the hacker or the owner of this account

**Comment by snipergaming888** [comment]
> umm hi I just need to know so my friend from school said that this is is his account and he said he got hacked but i think he is lying so are you the hacker or the owner of this account

I own this account.
